#!/bin/bash

echo "Build the docker container..."

docker build -t spring-boot-app .

echo "Built the docker container successfully. Proceeding to run the container..."

docker run -p 80:8080 spring-boot-app
